---
development:
  dialect: postgres
  database: ls_v2_development
  user: postgres
  password: root
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:root@127.0.0.1:5432/ls_v2_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:root@127.0.0.1:5432/ls_v2_production?sslmode=disable"}}
